# Generated by Django 4.2.5 on 2023-12-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_staticpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
